import requests

def import_deck(deck_path):
    # AnkiConnect endpoint URL
    anki_url = "http://localhost:8765"

    # Import deck request parameters
    params = {
        "action": "importDeck",
        "filename": deck_path
    }

    # Send POST request to AnkiConnect
    response = requests.post(anki_url, json=params)

    # Check if the request was successful
    if response.status_code == 200:
        print("Deck imported successfully.")
    else:
        print("Failed to import deck.")

# Path to the .apkg file generated by your script
deck_path = "Japanese_AI_Vocab_Deck.apkg"

# Call the function to import the deck
import_deck(deck_path)
