import requests
import os
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()


def import_deck(deck_path):
    # AnkiConnect endpoint URL to import the deck
    anki_url = os.getenv("ANKI_CONNECT_URL")

     # Get the absolute path of the deck file
    absolute_deck_path = os.path.abspath(deck_path)

    # Import deck request parameters
    params = {
        "action": "importPackage",
         "params" : {
          "path": absolute_deck_path
         }
    }

    # Send POST request to AnkiConnect
    response = requests.post(anki_url, json=params, )

    # Check if the request was successful
    if response.status_code == 200:
        print("Deck imported successfully.")
        print(response.json())

        # delete all files in the files directory at the same level as this script
        for file in os.listdir("./files"):
            file_path = os.path.join("./files", file)
            if os.path.isfile(file_path):
                os.remove(file_path)

        # delete the words.txt file at the same level as this script
        if os.path.exists("../words.txt"):
            os.remove("../words.txt")
           
        else:
              print("The file does not exist. Please clear you text file manually before running the script again.")



        # make a new words.txt file
        with open("../words.txt", "w") as file:
            file.write("")
      
    else:
        print("Failed to import deck.")

# Path to the .apkg file generated by your script
deck_path = "./files/Japanese_AI_Vocab_Deck.apkg"

# Call the function to import the deck
import_deck(deck_path)
