import sys
import os

# 現在のファイルのディレクトリの親ディレクトリをsys.pathに追加
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import import_deck
from variables import ANKI_DECK_NAME  # Import the variable from variables.py

# Path to the .apkg file generated by your script
print(f"wow ANKI_DECK_NAME: {ANKI_DECK_NAME}")
deck_name = ANKI_DECK_NAME
deck_path = f"./files/{deck_name}.apkg"
name_of_text_file = "words"

# Call the function to import the deck
import_deck(deck_path, name_of_text_file)