import sys
import os

# 現在のファイルのディレクトリの親ディレクトリをsys.pathに追加
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import import_deck

from dotenv import load_dotenv

load_dotenv()



# Path to the .apkg file generated by your script
deck_name = os.getenv("ANKI_DECK_NAME", "Japanese_AI_Vocab_Deck")
deck_path = f"./files/{deck_name}.apkg"
name_of_text_file = "words"

# Call the function to import the deck
import_deck(deck_path, name_of_text_file)