import sys
import os

# 現在のファイルのディレクトリの親ディレクトリをsys.pathに追加
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from utils import import_deck

# Path to the .apkg file generated by your script
deck_path = "./files/Japanese_AI_Sentance_Deck.apkg"
name_of_text_file = "sentances"

# Call the function to import the deck
import_deck(deck_path, name_of_text_file)